version: '3.9'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/apps
    ports:
      - 8000:8000
      - 5432:5432
    depends_on:
      - db

  db:
    image: postgres:15.1-alpine
    volumes:
      - postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_HOST_AUTH_METHOD=POSTGRES_HOST_AUTH_METHOD
      - POSTGRES_DATABASE=POSTGRES_DATABASE
      - POSTGRES_USER=POSTGRES_USER
      - POSTGRES_PASSWORD=POSTGRES_PASSWORD
    env_file:
      - ./.env

volumes:
  postgres:
